/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ldfygwjtppcskevcrypr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZnlnd2p0cHBjc2tldmNyeXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MjAxODUsImV4cCI6MjA5MjM5NjE4NX0.TxFH5AiC6ripMw8xxNB4nNJKMrS6ivUe3sHEusN--k0"